### ISSUE TITLE
Import hangs up

### ISSUE THREAD

**Issue by pentiumoverdrive** [brdude/pulp_centos_errata_import#19]
I started clean without any syncjobs running from foreman/katello but I gave up import after 14h (it was probably hung up for ~13.5h).

How can I troubleshoot this?

**Command:**
errata_import.pl  --errata=errata.latest.xml --user=admin --password=*** --debug --rhsa-oval=com.redhat.rhsa-all.xml --include-repo=ORG-CentOS-os_x86_64

See attached debug output (not really useful though).
[debug.txt](https://github.com/brdude/pulp_centos_errata_import/files/591210/debug.txt)

I also ran a strace, and this is where it hangs:

read(3, "\33[0m+---------------------------"..., 8192) = 4096
read(3, "\33[2A\33[J[\\]\nWaiting to begin...\n\33"..., 8192) = 4096
read(3, 

Looking like its waiting for pulp?
I went into pulp and killed all tasks, restarted the import and ended up with the import waiting again.
Now the only pulp task is the following:

`Operations:  import_upload
Resources:   ORG-CentOS-os_x86_64 (repository)
State:       Waiting
Start Time:  Unstarted
Finish Time: Incomplete
Task Id:     51598086-8eea-49f9-99b2-e1dd19432d7e
`

When I cancel the task, the import continues to the next errata but hangs there again.

**Comment by pentiumoverdrive** [comment]
I cleaned out all tasks, restarted pulp services, initiated a sync and then ran the errata_import.pl again, and its actually working. So, not really sure if the script is to blame, maybe it can at least display the "waiting output" from pulp, dunno.

**Comment by rdrgmnzs** [comment]
Closing for now, please re-open if you hit this once again.
