### ISSUE TITLE
Installable Errata is empty

### ISSUE THREAD

**Issue by ghost** [brdude/pulp_centos_errata_import#2]
After a sync with pulp_centos_errata_import the erratas are imported into "Errata" section, but the summary "Installable Errata" (Security/Bug Fix/Enhancement) on the host pages is still empty and will never be filled.

**Comment by rdrgmnzs** [comment]
This has been fixed on the latest commit ( https://github.com/brdude/pulp_centos_errata_import/commit/d0030d8681459ccd114c843230a65a1260fb7b83 ). Note that you will have to manually delete the errata from pulp and have it be re-created.

**Comment by ghost** [comment]
Thanks, it's working now. A perl plug-in more needs to be installed after your modification: perl-Switch. It can be added to the front page documentation.

**Comment by rdrgmnzs** [comment]
Thanks, I'll add that now.
