### ISSUE TITLE
No errata shown

### ISSUE THREAD

**Issue by storm49152** [brdude/pulp_centos_errata_import#21]
Hi,

I'm using Katello-3.3, Foreman-1.14.2, pulp-2.10.3 and Mondodb-2.6.12 on CentOS-7.3.
When I use the script in debug mode it shows that errata is found for packages and is uploaded for e.g. extras and updates. In the Mongodb database I can see errata in collection "units.erratum", but when I check Foreman it says there are no errata. Is this an issue with Foreman, or .. ?

**Comment by demueller** [comment]
Did u try to sync the repo again after the script run?

**Comment by storm49152** [comment]
Ah, no I didn't. I've just synced the base, extras and updates repos again and now it shows errata for all repos. Thanks!
