### ISSUE TITLE
Mistake in section

### ISSUE THREAD

**Issue by demueller** [brdude/pulp_centos_errata_import#23]
Authentication

pulp-admin must authenticate to pulp. This authentication information can be provided to pulp-admin in three ways.

User certificate (~/.pulp/user-cert.pem) RECOMMENDED
If you are using this script with katello, the foreman-installer creates a certificate suitable for use with pulp. You can use the cert by doing the following:
```shell
sudo cat /etc/pki/katello/certs/pulp-client.crt /etc/pki/katello/private/pulp-client.key > ~/.pulp/user-cert.pem
chown 400 `~/pulp/user-cert.pem` - should be `~/.pulp/user-cert.pem`

**Comment by rdrgmnzs** [comment]
Fixed! Thanks for catching this.
