### ISSUE TITLE
Trying out your script

### ISSUE THREAD

**Issue by vidalinux** [brdude/pulp_centos_errata_import#3]
Hi,
First of all thanks for this script, I'm trying it now on my Katello 2.2 with the following repos:
1. Centos7 Base
2. Centos7 Updates
3. Centos7 Extras

Imported the file without issues but Errata doesn't show on my Katello/Foreman interface, do I miss something? Regards...

**Comment by rdrgmnzs** [comment]
Hi after the errata is imported you have to sync the repos again. Unfortunately I have not found a way around this. If this is not it please reopen this issue.

**Comment by vidalinux** [comment]
Do you mean removing the repo then adding it again and sync ?

**Comment by rdrgmnzs** [comment]
No, what I mean is by going to "content" > "Sync Status" selecting your repos and then syncronizing them again.
