### ISSUE TITLE
Removing Errata

### ISSUE THREAD

**Issue by sargenthp** [brdude/pulp_centos_errata_import#35]
I was wondering if there is a way to remove the errata after importing it in?

Foreman is not working with the errata that we imported in for CentOS very well and we just want to re-remove it.

Found the command:  pulp-admin rpm repo remove errata --before YYYY-MM-DD --repo-id ID

But I am having issues with my Smart Proxy sync because it is still trying to read in the errata and erroring out now.

**Comment by rdrgmnzs** [comment]
Hi unfortunately I have not used Foreman / Pulp for a few years now so I won't be able to help. I'll leave this up in case someone in the community is able to help.

**Comment by sargenthp** [comment]
Thank you for the reply.

I believe the command that I found did actually work.  It looks like we have an issue with the Foreman Smart Proxy instead.
