### ISSUE TITLE
Pulp returns empty string when searching for package with plus symbol

### ISSUE THREAD

**Issue by geronimodings** [brdude/pulp_centos_errata_import#4]
btw thanks for the script,

The issue I encountered was with a package that contains a plus character. 

DEBUG: Package: memtest86+-4.20-14.el7.x86_64.rpm -> memtest86+-4.20-14.el7.x86_64.rpm -> Default_Organization-Centos7_os-os_x86_64 
INFO: Creating errata for CEBA-2014:1181 (CentOS memtest86+ FASTTRACK BugFix Update) (1 of 2)
Use of uninitialized value $pkgdetails[4] in concatenation (.) or string at ./errata_import.pl line 195.
Use of uninitialized value in concatenation (.) or string at ./errata_import.pl line 195.
Use of uninitialized value in concatenation (.) or string at ./errata_import.pl line 195.
Use of uninitialized value in concatenation (.) or string at ./errata_import.pl line 195.
Use of uninitialized value in concatenation (.) or string at ./errata_import.pl line 195.
Use of uninitialized value in concatenation (.) or string at ./errata_import.pl line 195.
Use of uninitialized value in concatenation (.) or string at ./errata_import.pl line 210.
INFO: Command: erratum
Description: creates a new erratum

I narrowed down the Problem to line 193

``` perl
   @pkgdetails = `pulp-admin rpm repo content rpm --repo-id=$name2channel{$package} --match="filename=$package" --fields=name,version,release,epoch,arch,checksum,checksumtype | awk '{print \$2}'`;
```

when pulp admin tries to match a package with a plus character it returns nothing.
If you escape the plus like this: `memtest86\+-4.20-14.el7.x86_64.rpm` it returns the right package.

my fix would looks like this

``` perl
 my $temp = $package;
 $temp =~ s/\+/\\\+/g;
 @pkgdetails = `pulp-admin rpm repo content rpm --repo-id=$name2channel{$package} --match="filename=$temp" 
```

**Comment by rdrgmnzs** [comment]
Awesome thanks! I've included the fix in the script.
