### ISSUE TITLE
compatibility with pulp 2.6.2 and katello 2.4.0

### ISSUE THREAD

**Issue by fuco809** [brdude/pulp_centos_errata_import#5]
hi,

first of all, thanks for your work.

i tried it with a ready deployed katello installation in virtualbox (https://github.com/Katello/katello-deploy) on centos7 with pulp2.6.2 and katello2.4.0

when importing with the script i get following:
on most erratas: NOTICE: Skipping errata .... -- No packages found
some of the erratas: INFO: Creating errata for ... Importing into the repository, an internal error occurred on the Pulp server: RequestException: POST request on /pulp/api/v2/repositories/Default_Organization-centos-5_0-CEL6-R_CEL6/actions/import_upload/ failed with 500 - Connection attach timed out

do you have any hint on how to solve this ?

thanks in advance,
hannes

**Comment by geronimodings** [comment]
I also use Pulp 2.6.2 but I only tested the Script with katello 2.1, 2.2 and 2.3. There might be a problem with the pulp setup in the nightly build.

Sometimes Pulp has an inclination to just don't start jobs because the assigned worker hangs in a busy state. You cloud try to restart all katello-services with, you guessed it, "katello-service restart". This causes all current jobs to be cleaned up.

One way to find out where the problem could be is to do an errata import by hand and mimic the script.
That way you can see if the script builds the errata wrong as an example.

**Comment by fuco809** [comment]
thx, know it looks better, after restart of katello.

the "connection attach timed out" messages disappeared and this errata tasks succeded (importing into repository).
but actually they did not appear in the katello web gui (after doing a sync of the repo).
i will check it again tomorrow.

**Comment by rdrgmnzs** [comment]
Sorry currently I'm not able to look into what is going on there. Maybe try deleting the repo and re-creating it. Then re-running the script and then the sync. 

Sorry I'm just strapped for time currently and probably won't have time to dig into this for at least a month.

**Comment by fuco809** [comment]
i played around and found a solution.
the erratas where mapped to a content-view repo and not to the "base" repo itself. i copied the erratas to the base and then restart katello and sync the repo... now erratas are viewed in katello too.

here some commands i used for debugging this:
pulp-admin login -u admin --password=XYZ     ... get a session cert
pulp-admin repo list | grep -B 5 Erratum   ... get my repos where erratas available
pulp-admin repo list -s   ... show list of my repos
pulp-admin rpm repo content errata --match type=security --repo-id=REPO_X    ... list all security erratas in repo_x
pulp-admin rpm repo copy errata --from-repo-id=SRCREPO --to-repo-id=DSTREPO   ... copy erratas between repos
pulp-admin logout  ... remove the session cert

**Comment by rdrgmnzs** [comment]
Pull request #6 should give you a way to get around having to copy the errata from one repo to another and have the script only insert it to the repos you want.
