### ISSUE TITLE
Host still has updates available after applying errata

### ISSUE THREAD

**Issue by r0k5t4r** [brdude/pulp_centos_errata_import#9]
I'm not sure why but even errata is listed and can be applied to a host, running yum update on a machine still shows available updates. It seems that the script reports that errata is already in katello but searching for it doesn't show the errata. I'm running Katello 2.4.1 and modified the script a little bit so that pulp-admin can be run with username and password.

**Comment by eduardohki** [comment]
Hi, are you updating the repository after the errata import completion?

I observed this too, and I realized that Foreman must "generate aplicability" after updating both repository and content host. So you need to update your host via web GUI.

I hope this helps :)

**Comment by r0k5t4r** [comment]
Hi,

yes I did update the repo after importing the errata. How can i update a content host?

**Comment by eduardohki** [comment]
You have two options:

1) Update all packages available into Content Host package details:
Go into [Menu] Hosts > Content Hosts > (select your host) > Packages > Update All

2) Apply errata:
Go into [Menu] Content > Errata > (select the errata) > (select your host) > Apply

Both procedures run a "Regenerate Applicability" task after completion, which calculates if erratas are available to the hosts.

Please report here if your problem continues.

**Comment by rdrgmnzs** [comment]
@r0k5t4r closing this. Feel free to re-open if you still have the issue.
